tester:
  hosts:
    unit1:
      ansible_host: 192.168.2.110
      ansible_ssh_private_key_file: /home/vagrant/unit1

    unit2:
      ansible_host: 192.168.2.111
      ansible_ssh_private_key_file: /home/vagrant/unit2

    ubuntu: 
      ansible_host: 192.168.2.120
      ansible_ssh_private_key_file: /home/vagrant/ubuntu
