---
- name: playbook runing
  become: True
  hosts: unit1
  roles:

    - nginx-tls #install nginx server with ssl sertificates  
#    - nano # install nano 6.2 with hightlight
#    - docker.io # install latest docker 
#    - django # install django in venv environment
#    - dnsmasq # install DNS server with hosts file on units
#    - docker # docker docker-compose install - old version
#    - resize-logs # reduce logs to 10M and more free space
#    - general # install general soft and dependencies
#    - python3 # install python3.9 and pip3
#    - net-tools # install net-tools nmap traceroute

#      - apache2 # install apache2 with php modules
