- name: Apt update
  become: True
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Python3 pip venv install
  apt:
    pkg:
      - ca-certificates
      - software-properties-common
      - python3.9
      - python3-pip
      - python3-venv
    state: latest
