    - name: Apt update
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Key docker add
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Repository docker add
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable

    - name: Apt update
      apt:
        update_cache: yes

    - name: Install docker-ce
      apt:
        name: docker-ce

    - name: Fix docker permission
      ansible.builtin.file:
        path: /var/run/docker.sock
        mode: '0666'

    - name: Docker-compose download
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.3.4/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: +x
