---
     - name: apache restart
       ansible.builtin.service:
         name: apache2
         state: restarted

     - name: apache reload
       ansible.builtin.service:
         name: apache2
         state: reloaded
