- name: Apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: General soft install and dependencies
  apt:
    pkg:
      - acl
      - tree
      - libncurses-dev
      - gcc
      - make
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: latest
