---
     - name: nginx start
       ansible.builtin.service:
         name: nginx
         state: started

     - name: nginx restart
       ansible.builtin.service:
         name: nginx
         state: restarted
