---

  - name: Create directory django cms
    ansible.builtin.file:
      path: "{{ full_path }}"
      state: directory

  - name: Create venv environment
    command: python3 -m venv "{{ django_venv }}"
    args:
      chdir: "{{ full_path }}"
    register: result
  - debug: var=result
#    changed_when: result.rc == 0

  - name: install django in venv dir
    pip:
      name: django
      virtualenv: "{{ full_path }}/{{ django_venv }}"

  - name: start new project
    command: "{{ full_path }}/{{ django_venv }}/bin/django-admin startproject {{ django_project }} {{ full_path }}"
    failed_when: False
    register: result
#  - debug: var=result
    changed_when: result.rc == 0

  - name: replace string
    ansible.builtin.lineinfile:
      path: "{{ full_path }}/{{ django_project }}/settings.py"
      regexp: '^ALLOWED_HOSTS'
      line: ALLOWED_HOSTS = ['*']

#  - name: start server
#    become: True
#    shell: "source {{ full_path }}/{{ django_venv }}/bin/activate && python {{ full_path }}/manage.py runserver 192.168.0.110:8000"
#    args:
#      executable: /usr/bin/bash
