---

  - name: Create directory django cms
    ansible.builtin.file:
      path: "{{ full_path }}"
      state: directory

  - name: install django in venv dir
    pip:
      name: django
      virtualenv: "{{ full_path }}/{{ django_venv }}"

  - name: start new project
    command: "{{ full_path }}/{{ django_venv }}/bin/django-admin startproject {{ django_project }} {{ full_path }}"

  - name: add local host for settings.py
    ansible.builtin.replace:
      path: "{{ full_path }}/{{ django_project }}/settings.py"
      after: 'ALLOWED_HOSTS = []'
      replace: 'ALLOWED_HOSTS = [127.0.0.1]'

#  - name: Create venv environment
#    command: python3 -m venv "{{ django_venv }}"
#    args:
#      chdir: "{{ full_path }}"

#  - name: Activate venv
#    become: True
#    command: source "{{ full_path }}/{{ django_venv }}"/bin/activate
#    shell: . activate
#    args:
#      chdir: "{{ full_path }}/{{ django_venv }}/bin"
#      executable: /usr/bin/bash

#  - name: Django pip install
#    command: pip install django
    #  chdir: "{{ $PWD }}"

#  - name: test version
#    command: django-admin --version

#  - name: Create django project
#    ansible.builtin.command: django-admin startproject "{{ django_project }}"
#      chdir: "{{ django_cms }}"

#  - name: DB migration
#    ansible.builtin.command: python manage.py migrate
#      chdir: "{{ django_cms}}{{ django_project}}"

#  - name: Create superuser db
#    ansible.builtin.command: python manage.py create superuser
#      chdir: "{{ django_cms}}{{ django_project}}"

#  - name: add ALLOWED_HOSTS in settings.py
#  - name: Start server
