unit_reserve:
  hosts:
    unit1:
      ansible_host: 192.168.1.110
      ansible_ssh_private_key_file: /home/vagrant/unit1/private_key

    unit2:
      ansible_host: 192.168.1.111
      ansible_ssh_private_key_file: /home/vagrant/unit2/private_key

    unit3:
      ansible_host: 192.168.1.112
      ansible_ssh_private_key_file: /home/vagrant/unit3/private_key

units:
  hosts:
    web:
      ansible_host: 192.168.1.110
      ansible_ssh_private_key_file: /home/vagrant/unit1/private_key
