---
    - name: Apt update
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install net-tools
      apt:
        pkg:
          - net-tools
          - traceroute
          - nmap
        state: latest
